name: Rich-codex
on: [push]
permissions:
  contents: write
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version
      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Install project to generate image
        run: |
          uv sync
      - name: Generate latest terminal images with rich-codex
        uses: ewels/rich-codex@80de9de011c994f32274bb4cffee140567621d8e # v1.2.11
        with:
          commit_changes: "false"
          skip_git_checks: "true"
          clean_img_paths: |
            ./demo/latest.png
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd demo/
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c # v1.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: example-image
          force: true
          directory: ./demo/
