name: Rich-codex
on: [push]
jobs:
  rich_codex:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install Poetry
        run: |
          pipx install --pip-args=--constraint=.github/workflows/constraints.txt poetry
          poetry --version

      - name: Install project to generate image
        run: |
          poetry install

      - name: Generate latest terminal images with rich-codex
        uses: ewels/rich-codex@v1
        with:
          commit_changes: "false"
          clean_img_paths: |
            ./demo/latest.png

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd demo/
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git config --global --add safe.directory /github/workspace/demo
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: example-image
          force: true
          directory: ./demo/
